version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data1:/data/db
      - config1:/data/configdb
    ports:
      - "27017:27017"
volumes:
  data1:
  config1:
  
      